platform :ios, '7.0'
pod 'FlurrySDK', '~> 5.1'
##pod 'PAPasscode', '~> 0.3'
pod 'KeychainItemWrapper', '~> 1.2'
pod 'SDWebImage', '~> 3.6'
pod 'TBXML', '~> 1.5'
pod 'BJImageCropper', '~> 1.0'
pod 'SBJson', '~> 4.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'EGOTableViewPullRefresh', '~> 0.1'
pod 'Reachability', '~> 3.1'
##pod 'RESwitch', '~> 1.0'